export type Profesor = {
  idProfesor: number;
  apellidos: string;
  nombres?: string;
  nombreCompleto?: string;
  direccion?: string;
  fechaNacimiento?: Date;
  email?: string;
  telefono?: string;
  celular?: string;
  sexo?: string;
  valorHora: number;
  estado: boolean;
  coordinador: boolean;
  userName?: string;
  userPass?: string;
  accesoWeb: boolean;
  horarioSinProfesor: boolean;
  idSede?: string;
  userv?: string;
  passv?: string;
  nombreReniec?: string;
  nroDoc?: string;
  id_tipodoc?: number;
  token?: string;
};